# Generated by Django 5.2.17 on 2026-08-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_userdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF Document"),
                    ("text", "Text File"),
                    ("csv", "CSV Spreadsheet"),
                    ("web", "Web Page"),
                ],
                default="pdf",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userdocument",
            name="url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="userdocument",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="user_docs/"),
        ),
    ]
